# Generated by Django 5.2.5 on 2025-08-20 06:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="專案名稱")),
                ("description", models.TextField(blank=True, verbose_name="專案描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "source_file",
                    models.FileField(upload_to="uploads/csv/", verbose_name="上傳檔案"),
                ),
                (
                    "analysis_method",
                    models.CharField(
                        choices=[
                            ("HBF", "HBF (2012)"),
                            ("NCEER", "NCEER"),
                            ("AIJ", "AIJ"),
                            ("JRA", "JRA"),
                        ],
                        default="HBF",
                        max_length=10,
                        verbose_name="分析方法",
                    ),
                ),
                (
                    "em_value",
                    models.FloatField(
                        default=72,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="錘擊能量效率 Em (%)",
                    ),
                ),
                (
                    "unit_weight_unit",
                    models.CharField(
                        choices=[("t/m3", "t/m³"), ("kN/m3", "kN/m³")],
                        default="t/m3",
                        max_length=10,
                        verbose_name="統體單位重單位",
                    ),
                ),
                (
                    "use_fault_data",
                    models.BooleanField(default=True, verbose_name="使用斷層距離參數"),
                ),
                (
                    "fault_shapefile",
                    models.FileField(
                        blank=True,
                        help_text="若不上傳將使用系統預設的活動斷層資料",
                        null=True,
                        upload_to="uploads/shapefiles/",
                        verbose_name="斷層資料檔案",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待分析"),
                            ("processing", "分析中"),
                            ("completed", "已完成"),
                            ("error", "分析錯誤"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="錯誤訊息")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "分析專案",
                "verbose_name_plural": "分析專案",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoreholeData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("borehole_id", models.CharField(max_length=100, verbose_name="鑽孔編號")),
                ("twd97_x", models.FloatField(verbose_name="TWD97 X座標")),
                ("twd97_y", models.FloatField(verbose_name="TWD97 Y座標")),
                (
                    "surface_elevation",
                    models.FloatField(blank=True, null=True, verbose_name="地表高程 (m)"),
                ),
                (
                    "water_depth",
                    models.FloatField(default=0, verbose_name="地下水位深度 (m)"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="縣市"),
                ),
                (
                    "district",
                    models.CharField(blank=True, max_length=50, verbose_name="鄉鎮區"),
                ),
                (
                    "village",
                    models.CharField(blank=True, max_length=50, verbose_name="里"),
                ),
                (
                    "taipei_basin_zone",
                    models.CharField(blank=True, max_length=20, verbose_name="台北盆地微分區"),
                ),
                (
                    "base_mw",
                    models.FloatField(blank=True, null=True, verbose_name="基準地震規模 Mw"),
                ),
                (
                    "sds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="設計譜加速度係數 SDS"
                    ),
                ),
                (
                    "sms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="設計譜加速度係數 SMS"
                    ),
                ),
                (
                    "sd1",
                    models.FloatField(
                        blank=True, null=True, verbose_name="設計譜加速度係數 SD1"
                    ),
                ),
                (
                    "sm1",
                    models.FloatField(
                        blank=True, null=True, verbose_name="設計譜加速度係數 SM1"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=100, verbose_name="地震參數來源"),
                ),
                (
                    "nearby_fault",
                    models.CharField(blank=True, max_length=200, verbose_name="鄰近斷層"),
                ),
                (
                    "vs30",
                    models.FloatField(
                        blank=True, null=True, verbose_name="平均剪力波速 Vs30 (m/s)"
                    ),
                ),
                (
                    "site_class",
                    models.CharField(blank=True, max_length=20, verbose_name="地盤分類"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boreholes",
                        to="liquefaction.analysisproject",
                        verbose_name="所屬專案",
                    ),
                ),
            ],
            options={
                "verbose_name": "鑽孔資料",
                "verbose_name_plural": "鑽孔資料",
                "ordering": ["borehole_id"],
                "unique_together": {("project", "borehole_id")},
            },
        ),
        migrations.CreateModel(
            name="SoilLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("top_depth", models.FloatField(verbose_name="上限深度 (m)")),
                ("bottom_depth", models.FloatField(verbose_name="下限深度 (m)")),
                (
                    "sample_id",
                    models.CharField(blank=True, max_length=50, verbose_name="取樣編號"),
                ),
                (
                    "uscs",
                    models.CharField(blank=True, max_length=10, verbose_name="統一土壤分類"),
                ),
                (
                    "spt_n",
                    models.FloatField(blank=True, null=True, verbose_name="SPT-N值"),
                ),
                (
                    "unit_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="統體單位重 (t/m³)"
                    ),
                ),
                (
                    "water_content",
                    models.FloatField(blank=True, null=True, verbose_name="含水量 (%)"),
                ),
                (
                    "gravel_percent",
                    models.FloatField(blank=True, null=True, verbose_name="礫石含量 (%)"),
                ),
                (
                    "sand_percent",
                    models.FloatField(blank=True, null=True, verbose_name="砂土含量 (%)"),
                ),
                (
                    "silt_percent",
                    models.FloatField(blank=True, null=True, verbose_name="粉土含量 (%)"),
                ),
                (
                    "clay_percent",
                    models.FloatField(blank=True, null=True, verbose_name="黏土含量 (%)"),
                ),
                (
                    "fines_content",
                    models.FloatField(blank=True, null=True, verbose_name="細料含量 (%)"),
                ),
                (
                    "plastic_index",
                    models.FloatField(blank=True, null=True, verbose_name="塑性指數 (%)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "borehole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_layers",
                        to="liquefaction.boreholedata",
                        verbose_name="所屬鑽孔",
                    ),
                ),
            ],
            options={
                "verbose_name": "土層資料",
                "verbose_name_plural": "土層資料",
                "ordering": ["borehole", "top_depth"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_method",
                    models.CharField(
                        choices=[
                            ("HBF", "HBF (2012)"),
                            ("NCEER", "NCEER"),
                            ("AIJ", "AIJ"),
                            ("JRA", "JRA"),
                        ],
                        max_length=10,
                        verbose_name="分析方法",
                    ),
                ),
                (
                    "soil_depth",
                    models.FloatField(blank=True, null=True, verbose_name="土層深度 (m)"),
                ),
                (
                    "mid_depth",
                    models.FloatField(blank=True, null=True, verbose_name="土層中點深度 (m)"),
                ),
                (
                    "analysis_depth",
                    models.FloatField(blank=True, null=True, verbose_name="分析點深度 (m)"),
                ),
                (
                    "sigma_v",
                    models.FloatField(
                        blank=True, null=True, verbose_name="總垂直應力 σv (t/m²)"
                    ),
                ),
                (
                    "sigma_v_csr",
                    models.FloatField(
                        blank=True, null=True, verbose_name="有效垂直應力 σ'v (t/m²)"
                    ),
                ),
                (
                    "sigma_v_crr",
                    models.FloatField(
                        blank=True, null=True, verbose_name="CRR有效垂直應力 (t/m²)"
                    ),
                ),
                ("n60", models.FloatField(blank=True, null=True, verbose_name="N60")),
                (
                    "n1_60",
                    models.FloatField(blank=True, null=True, verbose_name="N1_60"),
                ),
                (
                    "n1_60cs",
                    models.FloatField(blank=True, null=True, verbose_name="N1_60cs"),
                ),
                (
                    "vs",
                    models.FloatField(
                        blank=True, null=True, verbose_name="剪力波速 Vs (m/s)"
                    ),
                ),
                (
                    "crr_7_5",
                    models.FloatField(blank=True, null=True, verbose_name="CRR7.5"),
                ),
                (
                    "mw_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計地震規模"),
                ),
                (
                    "a_value_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計地表加速度"),
                ),
                (
                    "sd_s_design",
                    models.FloatField(
                        blank=True, null=True, verbose_name="設計譜加速度 SD_S"
                    ),
                ),
                (
                    "sm_s_design",
                    models.FloatField(
                        blank=True, null=True, verbose_name="設計譜加速度 SM_S"
                    ),
                ),
                (
                    "msf_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計規模修正因子"),
                ),
                (
                    "rd_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計應力折減係數"),
                ),
                (
                    "csr_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計反覆剪應力比"),
                ),
                (
                    "crr_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計液化抗力"),
                ),
                (
                    "fs_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計安全係數"),
                ),
                (
                    "lpi_design",
                    models.FloatField(blank=True, null=True, verbose_name="設計液化潛能指數"),
                ),
                (
                    "mw_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小地震規模"),
                ),
                (
                    "a_value_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小地表加速度"),
                ),
                (
                    "sd_s_mid",
                    models.FloatField(
                        blank=True, null=True, verbose_name="中小譜加速度 SD_S"
                    ),
                ),
                (
                    "sm_s_mid",
                    models.FloatField(
                        blank=True, null=True, verbose_name="中小譜加速度 SM_S"
                    ),
                ),
                (
                    "msf_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小規模修正因子"),
                ),
                (
                    "rd_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小應力折減係數"),
                ),
                (
                    "csr_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小反覆剪應力比"),
                ),
                (
                    "crr_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小液化抗力"),
                ),
                (
                    "fs_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小安全係數"),
                ),
                (
                    "lpi_mid",
                    models.FloatField(blank=True, null=True, verbose_name="中小液化潛能指數"),
                ),
                (
                    "mw_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大地震規模"),
                ),
                (
                    "a_value_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大地表加速度"),
                ),
                (
                    "sd_s_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最大譜加速度 SD_S"
                    ),
                ),
                (
                    "sm_s_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最大譜加速度 SM_S"
                    ),
                ),
                (
                    "msf_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大規模修正因子"),
                ),
                (
                    "rd_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大應力折減係數"),
                ),
                (
                    "csr_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大反覆剪應力比"),
                ),
                (
                    "crr_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大液化抗力"),
                ),
                (
                    "fs_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大安全係數"),
                ),
                (
                    "lpi_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大液化潛能指數"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "soil_layer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_result",
                        to="liquefaction.soillayer",
                        verbose_name="所屬土層",
                    ),
                ),
            ],
            options={
                "verbose_name": "分析結果",
                "verbose_name_plural": "分析結果",
            },
        ),
    ]
