# Generated by Django 5.2.5 on 2025-08-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquefaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisproject",
            name="analysis_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HBF", "HBF (2012)"),
                    ("NCEER", "NCEER"),
                    ("AIJ", "AIJ"),
                    ("JRA", "JRA"),
                ],
                help_text="可在分析時選擇其他方法",
                max_length=10,
                null=True,
                verbose_name="預設分析方法",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analysisresult",
            unique_together={("soil_layer", "analysis_method")},
        ),
    ]
