# Generated by Django 5.2.5 on 2025-08-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquefaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="analysis_method",
            field=models.CharField(
                choices=[
                    ("HBF", "HBF (2012)"),
                    ("NCEER", "NCEER"),
                    ("AIJ", "AIJ"),
                    ("JRA", "JRA"),
                ],
                default="HBF",
                max_length=10,
                verbose_name="分析方法",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysisproject",
            name="fault_shapefile",
            field=models.FileField(
                blank=True,
                help_text="若不上傳將使用系統預設的活動斷層資料",
                null=True,
                upload_to="uploads/shapefiles/",
                verbose_name="斷層資料檔案",
            ),
        ),
    ]
