# Generated by Django 5.2.5 on 2025-08-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquefaction", "0002_alter_analysisproject_analysis_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soillayer",
            name="borehole_id_ref",
            field=models.CharField(blank=True, max_length=100, verbose_name="鑽孔編號參考"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="bulk_density",
            field=models.FloatField(blank=True, null=True, verbose_name="統體密度 (t/m³)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="d10",
            field=models.FloatField(blank=True, null=True, verbose_name="D10 (mm)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="d30",
            field=models.FloatField(blank=True, null=True, verbose_name="D30 (mm)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="d60",
            field=models.FloatField(blank=True, null=True, verbose_name="D60 (mm)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="ground_elevation",
            field=models.FloatField(blank=True, null=True, verbose_name="鑽孔地表高程 (m)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="liquid_limit",
            field=models.FloatField(blank=True, null=True, verbose_name="液性限度 (%)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="n_value",
            field=models.FloatField(blank=True, null=True, verbose_name="N_value"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="project_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="計畫名稱"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="specific_gravity",
            field=models.FloatField(blank=True, null=True, verbose_name="比重"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="test_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="試驗編號"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="twd97_x",
            field=models.FloatField(blank=True, null=True, verbose_name="TWD97_X"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="twd97_y",
            field=models.FloatField(blank=True, null=True, verbose_name="TWD97_Y"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="void_ratio",
            field=models.FloatField(blank=True, null=True, verbose_name="空隙比"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="water_depth",
            field=models.FloatField(blank=True, null=True, verbose_name="地下水位深度 (m)"),
        ),
    ]
