# Generated by Django 5.2.5 on 2025-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "liquefaction",
            "0003_soillayer_borehole_id_ref_soillayer_bulk_density_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="soillayer",
            name="FC",
            field=models.FloatField(blank=True, null=True, verbose_name="細料含量 (%)"),
        ),
    ]
