# Generated by Django 5.2.5 on 2025-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquefaction", "0004_soillayer_fc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soillayer",
            name="FC",
        ),
        migrations.AddField(
            model_name="soillayer",
            name="core_diameter",
            field=models.FloatField(blank=True, null=True, verbose_name="岩心直徑 (cm)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="core_length",
            field=models.FloatField(blank=True, null=True, verbose_name="岩心長度 (cm)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="d50",
            field=models.FloatField(blank=True, null=True, verbose_name="D50 (mm)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="dry_unit_weight",
            field=models.FloatField(blank=True, null=True, verbose_name="乾單位重 (t/m³)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="plastic_limit",
            field=models.FloatField(blank=True, null=True, verbose_name="塑性限度 (%)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="shrinkage_index",
            field=models.FloatField(blank=True, null=True, verbose_name="縮性指數 (%)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="specific_gravity_rock",
            field=models.FloatField(blank=True, null=True, verbose_name="比重(岩石)"),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="ucs",
            field=models.FloatField(
                blank=True, null=True, verbose_name="單軸壓縮強度 (kg/cm²)"
            ),
        ),
        migrations.AddField(
            model_name="soillayer",
            name="water_content_rock",
            field=models.FloatField(blank=True, null=True, verbose_name="含水量(岩石) (%)"),
        ),
    ]
