# Generated by Django 5.2.5 on 2025-08-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquefaction", "0005_remove_soillayer_fc_soillayer_core_diameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soillayer",
            name="aashto_classification",
            field=models.CharField(blank=True, max_length=10, verbose_name="AASHTO分類"),
        ),
    ]
