# Generated by Django 5.2.5 on 2025-08-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquefaction", "0006_soillayer_aashto_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="c1_factor",
            field=models.FloatField(blank=True, null=True, verbose_name="C1係數"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="c2_factor",
            field=models.FloatField(blank=True, null=True, verbose_name="C2係數"),
        ),
    ]
