# Generated by Django 5.2.5 on 2025-08-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquefaction", "0007_analysisresult_c1_factor_analysisresult_c2_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="soillayer",
            name="plastic_index_original",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="塑性指數原始值"
            ),
        ),
        migrations.AlterField(
            model_name="soillayer",
            name="plastic_index",
            field=models.FloatField(blank=True, null=True, verbose_name="塑性指數"),
        ),
    ]
